import { PortableText } from '@portabletext/react';

import { portableTextComponents } from '@/components/sanity/portableTextComponents';
import Constituent from '../constituent/constituent';
import { ArtworkImageZoom } from '../image/artwork-image-zoom';
import Avatar from '../constituent/avatar';

export default function Artwork({ artwork, preview = false }) {
  const slug = artwork?.slug;

  return (
    <article className="">
      <div className="flex items-start gap-12 p-20">
        <div className="w-[20rem] min-w-[20rem]">
          <ArtworkImageZoom artwork={artwork} />
        </div>
        <div className="">
          <div className="">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight leading-tight md:leading-none mb-6">
              {artwork.title}
            </h1>
            <div className="mb-6 text-4xl">{artwork.formattedDate}</div>
            <div className="mb-6">
              {artwork.primaryConstituent && (
                <Avatar constituent={artwork.primaryConstituent} />
              )}
            </div>
          </div>
          <div className="text-xl markdown">
            <PortableText
              value={artwork.description}
              components={portableTextComponents}
            />
            <div className="text-muted-foreground italic">
              This prototype content was generated by ChatGPT.
            </div>
          </div>
        </div>
      </div>
      <div className="mt-12 p-20 bg-neutral-900">
        <Constituent constituent={artwork.primaryConstituent} />
      </div>
    </article>
  );
}
